//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitLife_Gym_Management_System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitLife_Gym_Management_System.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _03e0eaca68783968a8d6eed199e67612 {
            get {
                object obj = ResourceManager.GetObject("03e0eaca68783968a8d6eed199e67612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0884ba540658a5ca938cbce43fb4166c {
            get {
                object obj = ResourceManager.GetObject("0884ba540658a5ca938cbce43fb4166c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0884ba540658a5ca938cbce43fb4166c1 {
            get {
                object obj = ResourceManager.GetObject("0884ba540658a5ca938cbce43fb4166c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_FitLife_Gym_Main_Menu_ {
            get {
                object obj = ResourceManager.GetObject("1 FitLife Gym Main Menu ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1000_F_325736897_lyouuiCkWI59SZAPGPLZ5OWQjw2Gw4qY {
            get {
                object obj = ResourceManager.GetObject("1000_F_325736897_lyouuiCkWI59SZAPGPLZ5OWQjw2Gw4qY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1000_F_325736897_lyouuiCkWI59SZAPGPLZ5OWQjw2Gw4qY1 {
            get {
                object obj = ResourceManager.GetObject("1000_F_325736897_lyouuiCkWI59SZAPGPLZ5OWQjw2Gw4qY1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1000_F_325736897_lyouuiCkWI59SZAPGPLZ5OWQjw2Gw4qY2 {
            get {
                object obj = ResourceManager.GetObject("1000_F_325736897_lyouuiCkWI59SZAPGPLZ5OWQjw2Gw4qY2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1000_F_325736897_lyouuiCkWI59SZAPGPLZ5OWQjw2Gw4qY3 {
            get {
                object obj = ResourceManager.GetObject("1000_F_325736897_lyouuiCkWI59SZAPGPLZ5OWQjw2Gw4qY3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15960d2910ce4415f0674563dcd8bdf9 {
            get {
                object obj = ResourceManager.GetObject("15960d2910ce4415f0674563dcd8bdf9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _159c38d9bd4ad7da66563978ea30542e {
            get {
                object obj = ResourceManager.GetObject("159c38d9bd4ad7da66563978ea30542e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _159c38d9bd4ad7da66563978ea30542e1 {
            get {
                object obj = ResourceManager.GetObject("159c38d9bd4ad7da66563978ea30542e1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _21b20e5f6832c5856a6a67b64cbaf6bf {
            get {
                object obj = ResourceManager.GetObject("21b20e5f6832c5856a6a67b64cbaf6bf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _383064cb29c1680599334bf1839c5a7e {
            get {
                object obj = ResourceManager.GetObject("383064cb29c1680599334bf1839c5a7e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _383064cb29c1680599334bf1839c5a7e1 {
            get {
                object obj = ResourceManager.GetObject("383064cb29c1680599334bf1839c5a7e1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _383064cb29c1680599334bf1839c5a7e2 {
            get {
                object obj = ResourceManager.GetObject("383064cb29c1680599334bf1839c5a7e2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _383064cb29c1680599334bf1839c5a7e3 {
            get {
                object obj = ResourceManager.GetObject("383064cb29c1680599334bf1839c5a7e3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _383064cb29c1680599334bf1839c5a7e4 {
            get {
                object obj = ResourceManager.GetObject("383064cb29c1680599334bf1839c5a7e4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3c1fcb17de8f3e60fb30980a40abc1ca {
            get {
                object obj = ResourceManager.GetObject("3c1fcb17de8f3e60fb30980a40abc1ca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6a08648cba8c35147db7595012f6c997 {
            get {
                object obj = ResourceManager.GetObject("6a08648cba8c35147db7595012f6c997", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6a08648cba8c35147db7595012f6c9971 {
            get {
                object obj = ResourceManager.GetObject("6a08648cba8c35147db7595012f6c9971", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6a08648cba8c35147db7595012f6c9972 {
            get {
                object obj = ResourceManager.GetObject("6a08648cba8c35147db7595012f6c9972", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _765ef2d512432921655aba400b38573f {
            get {
                object obj = ResourceManager.GetObject("765ef2d512432921655aba400b38573f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _765ef2d512432921655aba400b38573f1 {
            get {
                object obj = ResourceManager.GetObject("765ef2d512432921655aba400b38573f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _765ef2d512432921655aba400b38573f2 {
            get {
                object obj = ResourceManager.GetObject("765ef2d512432921655aba400b38573f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _765ef2d512432921655aba400b38573f3 {
            get {
                object obj = ResourceManager.GetObject("765ef2d512432921655aba400b38573f3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _862386ca6902ff918f5ff8c252613031 {
            get {
                object obj = ResourceManager.GetObject("862386ca6902ff918f5ff8c252613031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a7594c2628534d33e3c3c86f5503ca6e {
            get {
                object obj = ResourceManager.GetObject("a7594c2628534d33e3c3c86f5503ca6e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ADMIN_LOGIN {
            get {
                object obj = ResourceManager.GetObject("ADMIN LOGIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b842bc6e16a197194d5110aa1886cc5a {
            get {
                object obj = ResourceManager.GetObject("b842bc6e16a197194d5110aa1886cc5a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b842bc6e16a197194d5110aa1886cc5a1 {
            get {
                object obj = ResourceManager.GetObject("b842bc6e16a197194d5110aa1886cc5a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b842bc6e16a197194d5110aa1886cc5ahhh {
            get {
                object obj = ResourceManager.GetObject("b842bc6e16a197194d5110aa1886cc5ahhh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap canvas {
            get {
                object obj = ResourceManager.GetObject("canvas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fvsdeef {
            get {
                object obj = ResourceManager.GetObject("fvsdeef", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_axh5u4axh5u4axh5 {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_axh5u4axh5u4axh5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_e47523e47523e475 {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_e47523e47523e475", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_e47523e47523e4751 {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_e47523e47523e4751", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_fdup6vfdup6vfdup__1_ {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_fdup6vfdup6vfdup (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainmenu {
            get {
                object obj = ResourceManager.GetObject("mainmenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_vector_search_icon_png_image_318071 {
            get {
                object obj = ResourceManager.GetObject("pngtree-vector-search-icon-png-image_318071", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2026_06_09_102758 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2026-06-09 102758", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uuuu {
            get {
                object obj = ResourceManager.GetObject("uuuu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
